name: deploy and publish

concurrency:
  group: "deploy"
  cancel-in-progress: false

on:
  release:
    types: [created]

jobs:
  deploy-docs:
    permissions:
      contents: read
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 26
      - run: npm ci
      - name: build docs
        run: npm run docs
      - name: upload docs artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/
      - name: deploy docs
        uses: actions/deploy-pages@v4

  publish-npm:
    permissions:
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 26
      - run: npm ci
      - name: build package
        run: npm run build
      - name: publish package
        run: npm publish --provenance
